# teanga-wasm/Cargo.toml
[package]
name = "teanga-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core WASM dependencies
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web APIs
web-sys = { version = "0.3", features = [
  "console",
  "Performance",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
] }

# Teanga core library (without database features)
teanga = { path = "../teanga", default-features = false }

[profile.release]
opt-level = "s"          # Optimize for size
lto = true              # Link Time Optimization
codegen-units = 1       # Single codegen unit for better optimization
panic = "abort"         # Smaller binary size
strip = true           # Strip debug symbols

# WASM-specific optimizations
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--enable-mutable-globals"]

[features]
default = []