# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f teanga-py/requirements.txt ]; then pip install -r teanga-py/requirements.txt; fi
    - uses: PyO3/maturin-action@v1
      with:
        args: --release --out dist
        working-directory: ./teanga-py
    - name: Test with pytest
      working-directory: ./teanga-py
      run: |
        python -m pip install teanga --no-index --find-links dist --force-reinstall
        # Pytest loads `teanga` from the source folder, so we have to manually
        # copy the Rust code to the source folder to run the tests
        # cp /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/teanga_py03/* teanga_py03/
        pip install dist/*.whl
        python -m pytest
